"""Model catalog dataset featuring modern open-weight LLMs."""

from __future__ import annotations

from llm_advisor.models.schema import (
    ModelProfile,
    QualityClass,
    QuantizationLevel,
    QuantizationProfile,
    SpeedClass,
)


def get_default_catalog() -> list[ModelProfile]:
    """Return default curated collection of open-weight LLM profiles."""
    return [
        # --- Tiny Category (1B - 3.8B) ---
        ModelProfile(
            id="llama-3.2-1b-instruct",
            name="Llama 3.2 1B Instruct",
            family="Llama",
            parameter_count_billions=1.23,
            architecture="Dense Transformer",
            context_length=128000,
            supported_quantizations=[
                QuantizationProfile(
                    level=QuantizationLevel.FP16,
                    bits_per_weight=16.0,
                    file_size_gb=2.5,
                    recommended_ram_gb=4.0,
                    recommended_vram_gb=3.0,
                    quality_retention_percent=100.0,
                ),
                QuantizationProfile(
                    level=QuantizationLevel.Q8_0,
                    bits_per_weight=8.5,
                    file_size_gb=1.3,
                    recommended_ram_gb=2.5,
                    recommended_vram_gb=2.0,
                    quality_retention_percent=99.5,
                ),
                QuantizationProfile(
                    level=QuantizationLevel.Q4_K_M,
                    bits_per_weight=4.5,
                    file_size_gb=0.8,
                    recommended_ram_gb=1.8,
                    recommended_vram_gb=1.5,
                    quality_retention_percent=96.0,
                ),
            ],
            default_quantization=QuantizationLevel.Q4_K_M,
            reasoning_strength=5.5,
            coding_strength=5.0,
            general_chat_strength=6.5,
            multilingual_strength=6.0,
            instruction_following=7.0,
            speed_class=SpeedClass.BLAZING,
            quality_class=QualityClass.ENTRY,
            use_cases=["general_chat", "lightweight", "privacy", "fast_inference"],
            pros=[
                "Extremely low memory footprint",
                "Ultra-fast response time",
                "128K context support",
            ],
            cons=["Limited complex reasoning capabilities", "Small knowledge base"],
            license="Llama-3.2 Community License",
        ),
        ModelProfile(
            id="qwen2.5-1.5b-instruct",
            name="Qwen 2.5 1.5B Instruct",
            family="Qwen",
            parameter_count_billions=1.54,
            architecture="Dense Transformer",
            context_length=32768,
            supported_quantizations=[
                QuantizationProfile(
                    level=QuantizationLevel.Q8_0,
                    bits_per_weight=8.5,
                    file_size_gb=1.6,
                    recommended_ram_gb=3.0,
                    recommended_vram_gb=2.2,
                    quality_retention_percent=99.5,
                ),
                QuantizationProfile(
                    level=QuantizationLevel.Q4_K_M,
                    bits_per_weight=4.5,
                    file_size_gb=0.98,
                    recommended_ram_gb=2.0,
                    recommended_vram_gb=1.6,
                    quality_retention_percent=97.0,
                ),
            ],
            default_quantization=QuantizationLevel.Q4_K_M,
            reasoning_strength=6.2,
            coding_strength=6.0,
            general_chat_strength=7.0,
            multilingual_strength=8.5,
            instruction_following=7.5,
            speed_class=SpeedClass.BLAZING,
            quality_class=QualityClass.ENTRY,
            use_cases=["general_chat", "multilingual", "lightweight", "coding"],
            pros=["Best-in-class multilingual performance for size", "Surprising coding prowess"],
            cons=["Struggles with long multi-step math reasoning"],
            license="Apache-2.0",
        ),
        ModelProfile(
            id="llama-3.2-3b-instruct",
            name="Llama 3.2 3B Instruct",
            family="Llama",
            parameter_count_billions=3.21,
            architecture="Dense Transformer",
            context_length=128000,
            supported_quantizations=[
                QuantizationProfile(
                    level=QuantizationLevel.Q8_0,
                    bits_per_weight=8.5,
                    file_size_gb=3.4,
                    recommended_ram_gb=5.0,
                    recommended_vram_gb=4.0,
                    quality_retention_percent=99.5,
                ),
                QuantizationProfile(
                    level=QuantizationLevel.Q4_K_M,
                    bits_per_weight=4.5,
                    file_size_gb=2.0,
                    recommended_ram_gb=3.5,
                    recommended_vram_gb=2.8,
                    quality_retention_percent=97.0,
                ),
            ],
            default_quantization=QuantizationLevel.Q4_K_M,
            reasoning_strength=6.8,
            coding_strength=6.5,
            general_chat_strength=7.5,
            multilingual_strength=6.8,
            instruction_following=8.0,
            speed_class=SpeedClass.FAST,
            quality_class=QualityClass.MODERATE,
            use_cases=["general_chat", "coding", "rag", "privacy"],
            pros=["Excellent quality-to-size ratio", "Massive 128K context window"],
            cons=["Higher RAM requirement than 1B models"],
            license="Llama-3.2 Community License",
        ),
        ModelProfile(
            id="phi-3.5-mini-instruct",
            name="Phi 3.5 Mini 3.8B Instruct",
            family="Phi",
            parameter_count_billions=3.82,
            architecture="Dense Transformer",
            context_length=128000,
            supported_quantizations=[
                QuantizationProfile(
                    level=QuantizationLevel.Q8_0,
                    bits_per_weight=8.5,
                    file_size_gb=4.0,
                    recommended_ram_gb=6.0,
                    recommended_vram_gb=4.8,
                    quality_retention_percent=99.0,
                ),
                QuantizationProfile(
                    level=QuantizationLevel.Q4_K_M,
                    bits_per_weight=4.5,
                    file_size_gb=2.3,
                    recommended_ram_gb=4.0,
                    recommended_vram_gb=3.2,
                    quality_retention_percent=96.5,
                ),
            ],
            default_quantization=QuantizationLevel.Q4_K_M,
            reasoning_strength=8.0,
            coding_strength=7.5,
            general_chat_strength=7.2,
            multilingual_strength=6.0,
            instruction_following=8.2,
            speed_class=SpeedClass.FAST,
            quality_class=QualityClass.HIGH,
            use_cases=["reasoning", "coding", "rag"],
            pros=["Punching above weight class in logic and math", "Strong code generation"],
            cons=["Strict prompt template structure needed"],
            license="MIT",
        ),
        # --- Small Category (7B - 9B) ---
        ModelProfile(
            id="qwen2.5-7b-instruct",
            name="Qwen 2.5 7B Instruct",
            family="Qwen",
            parameter_count_billions=7.61,
            architecture="Dense Transformer",
            context_length=131072,
            supported_quantizations=[
                QuantizationProfile(
                    level=QuantizationLevel.Q8_0,
                    bits_per_weight=8.5,
                    file_size_gb=8.1,
                    recommended_ram_gb=11.0,
                    recommended_vram_gb=9.5,
                    quality_retention_percent=99.8,
                ),
                QuantizationProfile(
                    level=QuantizationLevel.Q5_K_M,
                    bits_per_weight=5.5,
                    file_size_gb=5.4,
                    recommended_ram_gb=8.0,
                    recommended_vram_gb=6.8,
                    quality_retention_percent=98.5,
                ),
                QuantizationProfile(
                    level=QuantizationLevel.Q4_K_M,
                    bits_per_weight=4.5,
                    file_size_gb=4.7,
                    recommended_ram_gb=7.0,
                    recommended_vram_gb=5.8,
                    quality_retention_percent=97.2,
                ),
                QuantizationProfile(
                    level=QuantizationLevel.Q3_K_M,
                    bits_per_weight=3.5,
                    file_size_gb=3.7,
                    recommended_ram_gb=5.5,
                    recommended_vram_gb=4.8,
                    quality_retention_percent=93.0,
                ),
            ],
            default_quantization=QuantizationLevel.Q4_K_M,
            reasoning_strength=8.4,
            coding_strength=8.7,
            general_chat_strength=8.5,
            multilingual_strength=9.0,
            instruction_following=8.9,
            speed_class=SpeedClass.MODERATE,
            quality_class=QualityClass.HIGH,
            use_cases=["coding", "general_chat", "reasoning", "rag"],
            pros=["Outstanding coding performance", "Top tier 7B general reasoning"],
            cons=["Memory hungry at Q8_0 precision"],
            license="Apache-2.0",
        ),
        ModelProfile(
            id="llama-3.1-8b-instruct",
            name="Llama 3.1 8B Instruct",
            family="Llama",
            parameter_count_billions=8.03,
            architecture="Dense Transformer",
            context_length=128000,
            supported_quantizations=[
                QuantizationProfile(
                    level=QuantizationLevel.Q8_0,
                    bits_per_weight=8.5,
                    file_size_gb=8.5,
                    recommended_ram_gb=12.0,
                    recommended_vram_gb=10.0,
                    quality_retention_percent=99.8,
                ),
                QuantizationProfile(
                    level=QuantizationLevel.Q4_K_M,
                    bits_per_weight=4.5,
                    file_size_gb=4.9,
                    recommended_ram_gb=7.5,
                    recommended_vram_gb=6.2,
                    quality_retention_percent=97.0,
                ),
            ],
            default_quantization=QuantizationLevel.Q4_K_M,
            reasoning_strength=8.2,
            coding_strength=8.1,
            general_chat_strength=8.6,
            multilingual_strength=7.5,
            instruction_following=8.8,
            speed_class=SpeedClass.MODERATE,
            quality_class=QualityClass.HIGH,
            use_cases=["general_chat", "coding", "rag", "privacy"],
            pros=["Industry standard baseline", "Great tool calling and agent support"],
            cons=["Slightly lower multilingual capacity than Qwen 2.5"],
            license="Llama-3.1 Community License",
        ),
        ModelProfile(
            id="deepseek-r1-distill-qwen-7b",
            name="DeepSeek R1 Distill Qwen 7B",
            family="DeepSeek",
            parameter_count_billions=7.61,
            architecture="Dense Transformer",
            context_length=131072,
            supported_quantizations=[
                QuantizationProfile(
                    level=QuantizationLevel.Q8_0,
                    bits_per_weight=8.5,
                    file_size_gb=8.1,
                    recommended_ram_gb=11.5,
                    recommended_vram_gb=9.5,
                    quality_retention_percent=99.7,
                ),
                QuantizationProfile(
                    level=QuantizationLevel.Q4_K_M,
                    bits_per_weight=4.5,
                    file_size_gb=4.7,
                    recommended_ram_gb=7.2,
                    recommended_vram_gb=6.0,
                    quality_retention_percent=97.0,
                ),
            ],
            default_quantization=QuantizationLevel.Q4_K_M,
            reasoning_strength=9.2,
            coding_strength=8.5,
            general_chat_strength=7.8,
            multilingual_strength=8.2,
            instruction_following=8.6,
            speed_class=SpeedClass.MODERATE,
            quality_class=QualityClass.FRONTIER,
            use_cases=["reasoning", "coding", "math"],
            pros=[
                "State-of-the-art chain-of-thought reasoning for 7B class",
                "Exceptional math solving",
            ],
            cons=["Generates longer verbose reasoning steps"],
            license="MIT",
        ),
        ModelProfile(
            id="phi-4",
            name="Phi-4 14B Instruct",
            family="Phi",
            parameter_count_billions=14.7,
            architecture="Dense Transformer",
            context_length=16384,
            supported_quantizations=[
                QuantizationProfile(
                    level=QuantizationLevel.Q8_0,
                    bits_per_weight=8.5,
                    file_size_gb=15.5,
                    recommended_ram_gb=19.0,
                    recommended_vram_gb=17.0,
                    quality_retention_percent=99.8,
                ),
                QuantizationProfile(
                    level=QuantizationLevel.Q4_K_M,
                    bits_per_weight=4.5,
                    file_size_gb=9.1,
                    recommended_ram_gb=13.0,
                    recommended_vram_gb=10.5,
                    quality_retention_percent=97.5,
                ),
            ],
            default_quantization=QuantizationLevel.Q4_K_M,
            reasoning_strength=9.3,
            coding_strength=8.8,
            general_chat_strength=8.4,
            multilingual_strength=7.2,
            instruction_following=9.0,
            speed_class=SpeedClass.MODERATE,
            quality_class=QualityClass.FRONTIER,
            use_cases=["reasoning", "coding", "technical_qa"],
            pros=["Phenomenal STEM and complex math capability", "High parameter efficiency"],
            cons=["Shorter default context window (16K)"],
            license="MIT",
        ),
        # --- Medium Category (14B - 32B) ---
        ModelProfile(
            id="qwen2.5-14b-instruct",
            name="Qwen 2.5 14B Instruct",
            family="Qwen",
            parameter_count_billions=14.7,
            architecture="Dense Transformer",
            context_length=131072,
            supported_quantizations=[
                QuantizationProfile(
                    level=QuantizationLevel.Q8_0,
                    bits_per_weight=8.5,
                    file_size_gb=15.5,
                    recommended_ram_gb=19.0,
                    recommended_vram_gb=17.0,
                    quality_retention_percent=99.9,
                ),
                QuantizationProfile(
                    level=QuantizationLevel.Q4_K_M,
                    bits_per_weight=4.5,
                    file_size_gb=9.0,
                    recommended_ram_gb=12.5,
                    recommended_vram_gb=10.5,
                    quality_retention_percent=97.5,
                ),
                QuantizationProfile(
                    level=QuantizationLevel.Q3_K_M,
                    bits_per_weight=3.5,
                    file_size_gb=7.2,
                    recommended_ram_gb=10.0,
                    recommended_vram_gb=8.5,
                    quality_retention_percent=94.0,
                ),
            ],
            default_quantization=QuantizationLevel.Q4_K_M,
            reasoning_strength=9.0,
            coding_strength=9.1,
            general_chat_strength=9.0,
            multilingual_strength=9.2,
            instruction_following=9.2,
            speed_class=SpeedClass.SLOW,
            quality_class=QualityClass.FRONTIER,
            use_cases=["coding", "reasoning", "general_chat", "rag"],
            pros=["Near 70B quality at half the memory footprint", "Superb coding proficiency"],
            cons=["Requires at least 12GB+ RAM/VRAM"],
            license="Apache-2.0",
        ),
        ModelProfile(
            id="qwen2.5-32b-instruct",
            name="Qwen 2.5 32B Instruct",
            family="Qwen",
            parameter_count_billions=32.5,
            architecture="Dense Transformer",
            context_length=131072,
            supported_quantizations=[
                QuantizationProfile(
                    level=QuantizationLevel.Q8_0,
                    bits_per_weight=8.5,
                    file_size_gb=34.0,
                    recommended_ram_gb=40.0,
                    recommended_vram_gb=36.0,
                    quality_retention_percent=99.9,
                ),
                QuantizationProfile(
                    level=QuantizationLevel.Q4_K_M,
                    bits_per_weight=4.5,
                    file_size_gb=20.0,
                    recommended_ram_gb=26.0,
                    recommended_vram_gb=22.0,
                    quality_retention_percent=98.0,
                ),
                QuantizationProfile(
                    level=QuantizationLevel.Q3_K_M,
                    bits_per_weight=3.5,
                    file_size_gb=15.8,
                    recommended_ram_gb=20.0,
                    recommended_vram_gb=18.0,
                    quality_retention_percent=94.5,
                ),
            ],
            default_quantization=QuantizationLevel.Q4_K_M,
            reasoning_strength=9.4,
            coding_strength=9.5,
            general_chat_strength=9.3,
            multilingual_strength=9.4,
            instruction_following=9.5,
            speed_class=SpeedClass.SLOW,
            quality_class=QualityClass.FRONTIER,
            use_cases=["coding", "reasoning", "general_chat", "rag"],
            pros=[
                "Matches top proprietary models in coding & math",
                "Incredible instruction fidelity",
            ],
            cons=["Requires 24GB+ VRAM or 32GB+ system RAM"],
            license="Apache-2.0",
        ),
        # --- Large Category (70B+) ---
        ModelProfile(
            id="llama-3.1-70b-instruct",
            name="Llama 3.1 70B Instruct",
            family="Llama",
            parameter_count_billions=70.6,
            architecture="Dense Transformer",
            context_length=128000,
            supported_quantizations=[
                QuantizationProfile(
                    level=QuantizationLevel.Q8_0,
                    bits_per_weight=8.5,
                    file_size_gb=75.0,
                    recommended_ram_gb=84.0,
                    recommended_vram_gb=80.0,
                    quality_retention_percent=99.9,
                ),
                QuantizationProfile(
                    level=QuantizationLevel.Q4_K_M,
                    bits_per_weight=4.5,
                    file_size_gb=42.5,
                    recommended_ram_gb=50.0,
                    recommended_vram_gb=46.0,
                    quality_retention_percent=98.5,
                ),
                QuantizationProfile(
                    level=QuantizationLevel.Q2_K,
                    bits_per_weight=2.5,
                    file_size_gb=25.0,
                    recommended_ram_gb=32.0,
                    recommended_vram_gb=28.0,
                    quality_retention_percent=88.0,
                ),
            ],
            default_quantization=QuantizationLevel.Q4_K_M,
            reasoning_strength=9.6,
            coding_strength=9.4,
            general_chat_strength=9.7,
            multilingual_strength=8.8,
            instruction_following=9.7,
            speed_class=SpeedClass.VERY_SLOW,
            quality_class=QualityClass.FRONTIER,
            use_cases=["reasoning", "coding", "general_chat", "rag"],
            pros=[
                "True frontier level intelligence",
                "Deep comprehension and complex multi-agent execution",
            ],
            cons=["Extremely heavy RAM/VRAM requirements (48GB+ VRAM ideal)"],
            license="Llama-3.1 Community License",
        ),
    ]
